# This workflow runs in a dockerless situation for now!
# Adding flows for docker environment would be really appreciated.

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7 # may need to change
    
    container:
      image: ruby:2.6.2
      env:
        RAILS_ENV: development
        MYSQL_HOST: mysql
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        bundle install
        apt install -y yarn nodejs
        yarn install --check-files
    - name: Set Database
      run: rails db:setup
    - name: Run tests
      run: rails t
