# This workflow runs in a dockerless situation for now!
# Adding flows for docker environment would be really appreciated.

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    container: ahis1503/nuita
    
    services:
      mysql:
        image: mysql:5.7 # may need to change
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        yarn install --check-files
        bundle install
    - name: Set Database
      run: |
        export MYSQL_HOST=mysql
        export RAILS_ENV=development
        rails db:setup
    - name: Run tests
      run: rails t
